### ISSUE TITLE
Would you be happy for this code to be changed to a more open license such as MIT or GPL?  Kind regards,

### ISSUE THREAD

**Issue by Edwin10151** [jwlodek/py_cui_2048#3]

**Comment by jwlodek** [comment]
I don't think I would mind, is there a reason you wanted such a more permissive license?

**Comment by Edwin10151** [comment]
It is because I would like to use part of your code in my competition and MIT or GPL will be accepted by them.

**Comment by Edwin10151** [comment]
Sir?

**Comment by jwlodek** [comment]
Done.
